// Autogenerated from Pigeon (v24.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

enum InputImageType {
  file,
  bytes,
}

enum ImageLabelerType {
  base,
  local,
  remote,
}

/// Data of image required when creating image from bytes.
class InputImageMetadataMessage {
  InputImageMetadataMessage({
    required this.width,
    required this.height,
    required this.rotation,
    required this.format,
    required this.bytesPerRow,
  });

  int width;

  int height;

  /// Image rotation in degree.
  ///
  /// Not used on iOS.
  int rotation;

  /// Format of the input image.
  ///
  /// Android supports
  /// - [InputImageFormat.nv21]
  /// - [InputImageFormat.yuv_420_888]
  /// - [InputImageFormat.yv12]
  /// as described in [here](https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage.ImageFormat).
  ///
  /// iOS supports
  /// - [InputImageFormat.yuv420]
  /// - [InputImageFormat.bgra8888]
  int format;

  /// The row stride for color plane, in bytes.
  ///
  /// Not used on Android.
  int bytesPerRow;

  Object encode() {
    return <Object?>[
      width,
      height,
      rotation,
      format,
      bytesPerRow,
    ];
  }

  static InputImageMetadataMessage decode(Object result) {
    result as List<Object?>;
    return InputImageMetadataMessage(
      width: result[0]! as int,
      height: result[1]! as int,
      rotation: result[2]! as int,
      format: result[3]! as int,
      bytesPerRow: result[4]! as int,
    );
  }
}

class InputImageMessage {
  InputImageMessage({
    required this.type,
    this.filePath,
    this.bytes,
    this.metadata,
  });

  /// The type of image.
  InputImageType type;

  /// The file path to the image.
  String? filePath;

  /// The bytes of the image.
  Uint8List? bytes;

  /// The image data when creating an image of type = [InputImageType.bytes].
  InputImageMetadataMessage? metadata;

  Object encode() {
    return <Object?>[
      type,
      filePath,
      bytes,
      metadata,
    ];
  }

  static InputImageMessage decode(Object result) {
    result as List<Object?>;
    return InputImageMessage(
      type: result[0]! as InputImageType,
      filePath: result[1] as String?,
      bytes: result[2] as Uint8List?,
      metadata: result[3] as InputImageMetadataMessage?,
    );
  }
}

/// Base options for [ImageLabeler].
class ImageLabelerOptionsMessage {
  ImageLabelerOptionsMessage({
    required this.confidenceThreshold,
    required this.type,
  });

  /// The confidence threshold for labels returned by the image labeler.
  /// Labels returned by the image labeler will have a confidence level higher or equal to the given threshold.
  /// The value must be a floating-point value in the range [0, 1].
  /// Default value is set 0.5.
  double confidenceThreshold;

  /// Indicates that it uses Google's base model to process images.
  ImageLabelerType type;

  Object encode() {
    return <Object?>[
      confidenceThreshold,
      type,
    ];
  }

  static ImageLabelerOptionsMessage decode(Object result) {
    result as List<Object?>;
    return ImageLabelerOptionsMessage(
      confidenceThreshold: result[0]! as double,
      type: result[1]! as ImageLabelerType,
    );
  }
}

/// Represents a label detected in an image.
class ImageLabelMessage {
  ImageLabelMessage({
    required this.confidence,
    required this.label,
    required this.index,
  });

  /// The confidence(probability) given to label that was identified in image.
  double confidence;

  /// Label or title given for detected entity in image.
  String label;

  /// Index of label according to google's label map: https://developers.google.com/ml-kit/vision/image-labeling/label-map
  int index;

  Object encode() {
    return <Object?>[
      confidence,
      label,
      index,
    ];
  }

  static ImageLabelMessage decode(Object result) {
    result as List<Object?>;
    return ImageLabelMessage(
      confidence: result[0]! as double,
      label: result[1]! as String,
      index: result[2]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is InputImageType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ImageLabelerType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is InputImageMetadataMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is InputImageMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ImageLabelerOptionsMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ImageLabelMessage) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : InputImageType.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ImageLabelerType.values[value];
      case 131: 
        return InputImageMetadataMessage.decode(readValue(buffer)!);
      case 132: 
        return InputImageMessage.decode(readValue(buffer)!);
      case 133: 
        return ImageLabelerOptionsMessage.decode(readValue(buffer)!);
      case 134: 
        return ImageLabelMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ImageLabelDetectorApi {
  /// Constructor for [ImageLabelDetectorApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ImageLabelDetectorApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<ImageLabelMessage>> handleDetection(InputImageMessage inputImage) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.handleDetection$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[inputImage]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ImageLabelMessage>();
    }
  }

  Future<void> create(ImageLabelerOptionsMessage options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.create$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> manageModel(String modelName) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.manageModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[modelName]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> closeDetector(String id) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.closeDetector$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[id]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
