// Autogenerated from Pigeon (v24.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.google_mlkit_commons;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class Messages {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  public enum InputImageType {
    FILE(0),
    BYTES(1);

    final int index;

    InputImageType(final int index) {
      this.index = index;
    }
  }

  public enum ImageLabelerType {
    BASE(0),
    LOCAL(1),
    REMOTE(2);

    final int index;

    ImageLabelerType(final int index) {
      this.index = index;
    }
  }

  /**
   * Data of image required when creating image from bytes.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class InputImageMetadata {
    private @NonNull Long width;

    public @NonNull Long getWidth() {
      return width;
    }

    public void setWidth(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"width\" is null.");
      }
      this.width = setterArg;
    }

    private @NonNull Long height;

    public @NonNull Long getHeight() {
      return height;
    }

    public void setHeight(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"height\" is null.");
      }
      this.height = setterArg;
    }

    /**
     * Image rotation in degree.
     *
     * Not used on iOS.
     */
    private @NonNull Long rotation;

    public @NonNull Long getRotation() {
      return rotation;
    }

    public void setRotation(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"rotation\" is null.");
      }
      this.rotation = setterArg;
    }

    /**
     * Format of the input image.
     *
     * Android supports
     * - [InputImageFormat.nv21]
     * - [InputImageFormat.yuv_420_888]
     * - [InputImageFormat.yv12]
     * as described in [here](https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage.ImageFormat).
     *
     * iOS supports
     * - [InputImageFormat.yuv420]
     * - [InputImageFormat.bgra8888]
     */
    private @NonNull Long format;

    public @NonNull Long getFormat() {
      return format;
    }

    public void setFormat(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"format\" is null.");
      }
      this.format = setterArg;
    }

    /**
     * The row stride for color plane, in bytes.
     *
     * Not used on Android.
     */
    private @NonNull Long bytesPerRow;

    public @NonNull Long getBytesPerRow() {
      return bytesPerRow;
    }

    public void setBytesPerRow(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"bytesPerRow\" is null.");
      }
      this.bytesPerRow = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    InputImageMetadata() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      InputImageMetadata that = (InputImageMetadata) o;
      return width.equals(that.width) && height.equals(that.height) && rotation.equals(that.rotation) && format.equals(that.format) && bytesPerRow.equals(that.bytesPerRow);
    }

    @Override
    public int hashCode() {
      return Objects.hash(width, height, rotation, format, bytesPerRow);
    }

    public static final class Builder {

      private @Nullable Long width;

      @CanIgnoreReturnValue
      public @NonNull Builder setWidth(@NonNull Long setterArg) {
        this.width = setterArg;
        return this;
      }

      private @Nullable Long height;

      @CanIgnoreReturnValue
      public @NonNull Builder setHeight(@NonNull Long setterArg) {
        this.height = setterArg;
        return this;
      }

      private @Nullable Long rotation;

      @CanIgnoreReturnValue
      public @NonNull Builder setRotation(@NonNull Long setterArg) {
        this.rotation = setterArg;
        return this;
      }

      private @Nullable Long format;

      @CanIgnoreReturnValue
      public @NonNull Builder setFormat(@NonNull Long setterArg) {
        this.format = setterArg;
        return this;
      }

      private @Nullable Long bytesPerRow;

      @CanIgnoreReturnValue
      public @NonNull Builder setBytesPerRow(@NonNull Long setterArg) {
        this.bytesPerRow = setterArg;
        return this;
      }

      public @NonNull InputImageMetadata build() {
        InputImageMetadata pigeonReturn = new InputImageMetadata();
        pigeonReturn.setWidth(width);
        pigeonReturn.setHeight(height);
        pigeonReturn.setRotation(rotation);
        pigeonReturn.setFormat(format);
        pigeonReturn.setBytesPerRow(bytesPerRow);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(5);
      toListResult.add(width);
      toListResult.add(height);
      toListResult.add(rotation);
      toListResult.add(format);
      toListResult.add(bytesPerRow);
      return toListResult;
    }

    static @NonNull InputImageMetadata fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      InputImageMetadata pigeonResult = new InputImageMetadata();
      Object width = pigeonVar_list.get(0);
      pigeonResult.setWidth((Long) width);
      Object height = pigeonVar_list.get(1);
      pigeonResult.setHeight((Long) height);
      Object rotation = pigeonVar_list.get(2);
      pigeonResult.setRotation((Long) rotation);
      Object format = pigeonVar_list.get(3);
      pigeonResult.setFormat((Long) format);
      Object bytesPerRow = pigeonVar_list.get(4);
      pigeonResult.setBytesPerRow((Long) bytesPerRow);
      return pigeonResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class InputImageMessage {
    /** The type of image. */
    private @NonNull InputImageType type;

    public @NonNull InputImageType getType() {
      return type;
    }

    public void setType(@NonNull InputImageType setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"type\" is null.");
      }
      this.type = setterArg;
    }

    /** The file path to the image. */
    private @Nullable String filePath;

    public @Nullable String getFilePath() {
      return filePath;
    }

    public void setFilePath(@Nullable String setterArg) {
      this.filePath = setterArg;
    }

    /** The bytes of the image. */
    private @Nullable byte[] bytes;

    public @Nullable byte[] getBytes() {
      return bytes;
    }

    public void setBytes(@Nullable byte[] setterArg) {
      this.bytes = setterArg;
    }

    /** The image data when creating an image of type = [InputImageType.bytes]. */
    private @Nullable InputImageMetadata metadata;

    public @Nullable InputImageMetadata getMetadata() {
      return metadata;
    }

    public void setMetadata(@Nullable InputImageMetadata setterArg) {
      this.metadata = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    InputImageMessage() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      InputImageMessage that = (InputImageMessage) o;
      return type.equals(that.type) && Objects.equals(filePath, that.filePath) && Arrays.equals(bytes, that.bytes) && Objects.equals(metadata, that.metadata);
    }

    @Override
    public int hashCode() {
      int pigeonVar_result = Objects.hash(type, filePath, metadata);
      pigeonVar_result = 31 * pigeonVar_result + Arrays.hashCode(bytes);
      return pigeonVar_result;
    }

    public static final class Builder {

      private @Nullable InputImageType type;

      @CanIgnoreReturnValue
      public @NonNull Builder setType(@NonNull InputImageType setterArg) {
        this.type = setterArg;
        return this;
      }

      private @Nullable String filePath;

      @CanIgnoreReturnValue
      public @NonNull Builder setFilePath(@Nullable String setterArg) {
        this.filePath = setterArg;
        return this;
      }

      private @Nullable byte[] bytes;

      @CanIgnoreReturnValue
      public @NonNull Builder setBytes(@Nullable byte[] setterArg) {
        this.bytes = setterArg;
        return this;
      }

      private @Nullable InputImageMetadata metadata;

      @CanIgnoreReturnValue
      public @NonNull Builder setMetadata(@Nullable InputImageMetadata setterArg) {
        this.metadata = setterArg;
        return this;
      }

      public @NonNull InputImageMessage build() {
        InputImageMessage pigeonReturn = new InputImageMessage();
        pigeonReturn.setType(type);
        pigeonReturn.setFilePath(filePath);
        pigeonReturn.setBytes(bytes);
        pigeonReturn.setMetadata(metadata);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(4);
      toListResult.add(type);
      toListResult.add(filePath);
      toListResult.add(bytes);
      toListResult.add(metadata);
      return toListResult;
    }

    static @NonNull InputImageMessage fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      InputImageMessage pigeonResult = new InputImageMessage();
      Object type = pigeonVar_list.get(0);
      pigeonResult.setType((InputImageType) type);
      Object filePath = pigeonVar_list.get(1);
      pigeonResult.setFilePath((String) filePath);
      Object bytes = pigeonVar_list.get(2);
      pigeonResult.setBytes((byte[]) bytes);
      Object metadata = pigeonVar_list.get(3);
      pigeonResult.setMetadata((InputImageMetadata) metadata);
      return pigeonResult;
    }
  }

  /**
   * Base options for [ImageLabeler].
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class ImageLabelerOptionsMessage {
    /**
     * The confidence threshold for labels returned by the image labeler.
     * Labels returned by the image labeler will have a confidence level higher or equal to the given threshold.
     * The value must be a floating-point value in the range [0, 1].
     * Default value is set 0.5.
     */
    private @NonNull Double confidenceThreshold;

    public @NonNull Double getConfidenceThreshold() {
      return confidenceThreshold;
    }

    public void setConfidenceThreshold(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"confidenceThreshold\" is null.");
      }
      this.confidenceThreshold = setterArg;
    }

    /** Indicates that it uses Google's base model to process images. */
    private @NonNull ImageLabelerType type;

    public @NonNull ImageLabelerType getType() {
      return type;
    }

    public void setType(@NonNull ImageLabelerType setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"type\" is null.");
      }
      this.type = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ImageLabelerOptionsMessage() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ImageLabelerOptionsMessage that = (ImageLabelerOptionsMessage) o;
      return confidenceThreshold.equals(that.confidenceThreshold) && type.equals(that.type);
    }

    @Override
    public int hashCode() {
      return Objects.hash(confidenceThreshold, type);
    }

    public static final class Builder {

      private @Nullable Double confidenceThreshold;

      @CanIgnoreReturnValue
      public @NonNull Builder setConfidenceThreshold(@NonNull Double setterArg) {
        this.confidenceThreshold = setterArg;
        return this;
      }

      private @Nullable ImageLabelerType type;

      @CanIgnoreReturnValue
      public @NonNull Builder setType(@NonNull ImageLabelerType setterArg) {
        this.type = setterArg;
        return this;
      }

      public @NonNull ImageLabelerOptionsMessage build() {
        ImageLabelerOptionsMessage pigeonReturn = new ImageLabelerOptionsMessage();
        pigeonReturn.setConfidenceThreshold(confidenceThreshold);
        pigeonReturn.setType(type);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(2);
      toListResult.add(confidenceThreshold);
      toListResult.add(type);
      return toListResult;
    }

    static @NonNull ImageLabelerOptionsMessage fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ImageLabelerOptionsMessage pigeonResult = new ImageLabelerOptionsMessage();
      Object confidenceThreshold = pigeonVar_list.get(0);
      pigeonResult.setConfidenceThreshold((Double) confidenceThreshold);
      Object type = pigeonVar_list.get(1);
      pigeonResult.setType((ImageLabelerType) type);
      return pigeonResult;
    }
  }

  /**
   * Represents a label detected in an image.
   *
   * Generated class from Pigeon that represents data sent in messages.
   */
  public static final class ImageLabelMessage {
    /** The confidence(probability) given to label that was identified in image. */
    private @NonNull Double confidence;

    public @NonNull Double getConfidence() {
      return confidence;
    }

    public void setConfidence(@NonNull Double setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"confidence\" is null.");
      }
      this.confidence = setterArg;
    }

    /** Label or title given for detected entity in image. */
    private @NonNull String label;

    public @NonNull String getLabel() {
      return label;
    }

    public void setLabel(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"label\" is null.");
      }
      this.label = setterArg;
    }

    /** Index of label according to google's label map: https://developers.google.com/ml-kit/vision/image-labeling/label-map */
    private @NonNull Long index;

    public @NonNull Long getIndex() {
      return index;
    }

    public void setIndex(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"index\" is null.");
      }
      this.index = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    ImageLabelMessage() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      ImageLabelMessage that = (ImageLabelMessage) o;
      return confidence.equals(that.confidence) && label.equals(that.label) && index.equals(that.index);
    }

    @Override
    public int hashCode() {
      return Objects.hash(confidence, label, index);
    }

    public static final class Builder {

      private @Nullable Double confidence;

      @CanIgnoreReturnValue
      public @NonNull Builder setConfidence(@NonNull Double setterArg) {
        this.confidence = setterArg;
        return this;
      }

      private @Nullable String label;

      @CanIgnoreReturnValue
      public @NonNull Builder setLabel(@NonNull String setterArg) {
        this.label = setterArg;
        return this;
      }

      private @Nullable Long index;

      @CanIgnoreReturnValue
      public @NonNull Builder setIndex(@NonNull Long setterArg) {
        this.index = setterArg;
        return this;
      }

      public @NonNull ImageLabelMessage build() {
        ImageLabelMessage pigeonReturn = new ImageLabelMessage();
        pigeonReturn.setConfidence(confidence);
        pigeonReturn.setLabel(label);
        pigeonReturn.setIndex(index);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(3);
      toListResult.add(confidence);
      toListResult.add(label);
      toListResult.add(index);
      return toListResult;
    }

    static @NonNull ImageLabelMessage fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      ImageLabelMessage pigeonResult = new ImageLabelMessage();
      Object confidence = pigeonVar_list.get(0);
      pigeonResult.setConfidence((Double) confidence);
      Object label = pigeonVar_list.get(1);
      pigeonResult.setLabel((String) label);
      Object index = pigeonVar_list.get(2);
      pigeonResult.setIndex((Long) index);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129: {
          Object value = readValue(buffer);
          return value == null ? null : InputImageType.values()[((Long) value).intValue()];
        }
        case (byte) 130: {
          Object value = readValue(buffer);
          return value == null ? null : ImageLabelerType.values()[((Long) value).intValue()];
        }
        case (byte) 131:
          return InputImageMetadata.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 132:
          return InputImageMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 133:
          return ImageLabelerOptionsMessage.fromList((ArrayList<Object>) readValue(buffer));
        case (byte) 134:
          return ImageLabelMessage.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof InputImageType) {
        stream.write(129);
        writeValue(stream, value == null ? null : ((InputImageType) value).index);
      } else if (value instanceof ImageLabelerType) {
        stream.write(130);
        writeValue(stream, value == null ? null : ((ImageLabelerType) value).index);
      } else if (value instanceof InputImageMetadata) {
        stream.write(131);
        writeValue(stream, ((InputImageMetadata) value).toList());
      } else if (value instanceof InputImageMessage) {
        stream.write(132);
        writeValue(stream, ((InputImageMessage) value).toList());
      } else if (value instanceof ImageLabelerOptionsMessage) {
        stream.write(133);
        writeValue(stream, ((ImageLabelerOptionsMessage) value).toList());
      } else if (value instanceof ImageLabelMessage) {
        stream.write(134);
        writeValue(stream, ((ImageLabelMessage) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Generated interface from Pigeon that represents a handler of messages from Flutter. */
  public interface ImageLabelDetectorApi {

    void handleDetection(@NonNull InputImageMessage inputImage, @NonNull Result<List<ImageLabelMessage>> result);

    void create(@NonNull ImageLabelerOptionsMessage options);

    void manageModel(@NonNull String modelName);

    void closeDetector(@NonNull String id);

    /** The codec used by ImageLabelDetectorApi. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `ImageLabelDetectorApi` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable ImageLabelDetectorApi api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable ImageLabelDetectorApi api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.handleDetection" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                InputImageMessage inputImageArg = (InputImageMessage) args.get(0);
                Result<List<ImageLabelMessage>> resultCallback =
                    new Result<List<ImageLabelMessage>>() {
                      public void success(List<ImageLabelMessage> result) {
                        wrapped.add(0, result);
                        reply.reply(wrapped);
                      }

                      public void error(Throwable error) {
                        ArrayList<Object> wrappedError = wrapError(error);
                        reply.reply(wrappedError);
                      }
                    };

                api.handleDetection(inputImageArg, resultCallback);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.create" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                ImageLabelerOptionsMessage optionsArg = (ImageLabelerOptionsMessage) args.get(0);
                try {
                  api.create(optionsArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.manageModel" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String modelNameArg = (String) args.get(0);
                try {
                  api.manageModel(modelNameArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.closeDetector" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                String idArg = (String) args.get(0);
                try {
                  api.closeDetector(idArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
}
