// Autogenerated from Pigeon (v24.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, PGNInputImageType) {
  PGNInputImageTypeFile = 0,
  PGNInputImageTypeBytes = 1,
};

/// Wrapper for PGNInputImageType to allow for nullability.
@interface PGNInputImageTypeBox : NSObject
@property(nonatomic, assign) PGNInputImageType value;
- (instancetype)initWithValue:(PGNInputImageType)value;
@end

typedef NS_ENUM(NSUInteger, PGNImageLabelerType) {
  PGNImageLabelerTypeBase = 0,
  PGNImageLabelerTypeLocal = 1,
  PGNImageLabelerTypeRemote = 2,
};

/// Wrapper for PGNImageLabelerType to allow for nullability.
@interface PGNImageLabelerTypeBox : NSObject
@property(nonatomic, assign) PGNImageLabelerType value;
- (instancetype)initWithValue:(PGNImageLabelerType)value;
@end

@class PGNInputImageMetadata;
@class PGNInputImageMessage;
@class PGNImageLabelerOptionsMessage;
@class PGNImageLabelMessage;

/// Data of image required when creating image from bytes.
@interface PGNInputImageMetadata : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithWidth:(NSInteger )width
    height:(NSInteger )height
    rotation:(NSInteger )rotation
    format:(NSInteger )format
    bytesPerRow:(NSInteger )bytesPerRow;
@property(nonatomic, assign) NSInteger  width;
@property(nonatomic, assign) NSInteger  height;
/// Image rotation in degree.
///
/// Not used on iOS.
@property(nonatomic, assign) NSInteger  rotation;
/// Format of the input image.
///
/// Android supports
/// - [InputImageFormat.nv21]
/// - [InputImageFormat.yuv_420_888]
/// - [InputImageFormat.yv12]
/// as described in [here](https://developers.google.com/android/reference/com/google/mlkit/vision/common/InputImage.ImageFormat).
///
/// iOS supports
/// - [InputImageFormat.yuv420]
/// - [InputImageFormat.bgra8888]
@property(nonatomic, assign) NSInteger  format;
/// The row stride for color plane, in bytes.
///
/// Not used on Android.
@property(nonatomic, assign) NSInteger  bytesPerRow;
@end

@interface PGNInputImageMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithType:(PGNInputImageType)type
    filePath:(nullable NSString *)filePath
    bytes:(nullable FlutterStandardTypedData *)bytes
    metadata:(nullable PGNInputImageMetadata *)metadata;
/// The type of image.
@property(nonatomic, assign) PGNInputImageType type;
/// The file path to the image.
@property(nonatomic, copy, nullable) NSString * filePath;
/// The bytes of the image.
@property(nonatomic, strong, nullable) FlutterStandardTypedData * bytes;
/// The image data when creating an image of type = [InputImageType.bytes].
@property(nonatomic, strong, nullable) PGNInputImageMetadata * metadata;
@end

/// Base options for [ImageLabeler].
@interface PGNImageLabelerOptionsMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithConfidenceThreshold:(double )confidenceThreshold
    type:(PGNImageLabelerType)type;
/// The confidence threshold for labels returned by the image labeler.
/// Labels returned by the image labeler will have a confidence level higher or equal to the given threshold.
/// The value must be a floating-point value in the range [0, 1].
/// Default value is set 0.5.
@property(nonatomic, assign) double  confidenceThreshold;
/// Indicates that it uses Google's base model to process images.
@property(nonatomic, assign) PGNImageLabelerType type;
@end

/// Represents a label detected in an image.
@interface PGNImageLabelMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithConfidence:(double )confidence
    label:(NSString *)label
    index:(NSInteger )index;
/// The confidence(probability) given to label that was identified in image.
@property(nonatomic, assign) double  confidence;
/// Label or title given for detected entity in image.
@property(nonatomic, copy) NSString * label;
/// Index of label according to google's label map: https://developers.google.com/ml-kit/vision/image-labeling/label-map
@property(nonatomic, assign) NSInteger  index;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *PGNGetMessagesCodec(void);

@protocol PGNImageLabelDetectorApi
- (void)handleDetectionInputImage:(PGNInputImageMessage *)inputImage completion:(void (^)(NSArray<PGNImageLabelMessage *> *_Nullable, FlutterError *_Nullable))completion;
- (void)createOptions:(PGNImageLabelerOptionsMessage *)options error:(FlutterError *_Nullable *_Nonnull)error;
- (void)manageModelModelName:(NSString *)modelName error:(FlutterError *_Nullable *_Nonnull)error;
- (void)closeDetectorId:(NSString *)id error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpPGNImageLabelDetectorApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNImageLabelDetectorApi> *_Nullable api);

extern void SetUpPGNImageLabelDetectorApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNImageLabelDetectorApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
