// Autogenerated from Pigeon (v24.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "messages.g.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation PGNInputImageTypeBox
- (instancetype)initWithValue:(PGNInputImageType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation PGNImageLabelerTypeBox
- (instancetype)initWithValue:(PGNImageLabelerType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface PGNInputImageMetadataMessage ()
+ (PGNInputImageMetadataMessage *)fromList:(NSArray<id> *)list;
+ (nullable PGNInputImageMetadataMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PGNInputImageMessage ()
+ (PGNInputImageMessage *)fromList:(NSArray<id> *)list;
+ (nullable PGNInputImageMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PGNImageLabelerOptionsMessage ()
+ (PGNImageLabelerOptionsMessage *)fromList:(NSArray<id> *)list;
+ (nullable PGNImageLabelerOptionsMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface PGNImageLabelMessage ()
+ (PGNImageLabelMessage *)fromList:(NSArray<id> *)list;
+ (nullable PGNImageLabelMessage *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation PGNInputImageMetadataMessage
+ (instancetype)makeWithWidth:(NSInteger )width
    height:(NSInteger )height
    rotation:(NSInteger )rotation
    format:(NSInteger )format
    bytesPerRow:(NSInteger )bytesPerRow {
  PGNInputImageMetadataMessage* pigeonResult = [[PGNInputImageMetadataMessage alloc] init];
  pigeonResult.width = width;
  pigeonResult.height = height;
  pigeonResult.rotation = rotation;
  pigeonResult.format = format;
  pigeonResult.bytesPerRow = bytesPerRow;
  return pigeonResult;
}
+ (PGNInputImageMetadataMessage *)fromList:(NSArray<id> *)list {
  PGNInputImageMetadataMessage *pigeonResult = [[PGNInputImageMetadataMessage alloc] init];
  pigeonResult.width = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.height = [GetNullableObjectAtIndex(list, 1) integerValue];
  pigeonResult.rotation = [GetNullableObjectAtIndex(list, 2) integerValue];
  pigeonResult.format = [GetNullableObjectAtIndex(list, 3) integerValue];
  pigeonResult.bytesPerRow = [GetNullableObjectAtIndex(list, 4) integerValue];
  return pigeonResult;
}
+ (nullable PGNInputImageMetadataMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNInputImageMetadataMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.width),
    @(self.height),
    @(self.rotation),
    @(self.format),
    @(self.bytesPerRow),
  ];
}
@end

@implementation PGNInputImageMessage
+ (instancetype)makeWithType:(PGNInputImageType)type
    filePath:(nullable NSString *)filePath
    bytes:(nullable FlutterStandardTypedData *)bytes
    metadata:(nullable PGNInputImageMetadataMessage *)metadata {
  PGNInputImageMessage* pigeonResult = [[PGNInputImageMessage alloc] init];
  pigeonResult.type = type;
  pigeonResult.filePath = filePath;
  pigeonResult.bytes = bytes;
  pigeonResult.metadata = metadata;
  return pigeonResult;
}
+ (PGNInputImageMessage *)fromList:(NSArray<id> *)list {
  PGNInputImageMessage *pigeonResult = [[PGNInputImageMessage alloc] init];
  PGNInputImageTypeBox *boxedPGNInputImageType = GetNullableObjectAtIndex(list, 0);
  pigeonResult.type = boxedPGNInputImageType.value;
  pigeonResult.filePath = GetNullableObjectAtIndex(list, 1);
  pigeonResult.bytes = GetNullableObjectAtIndex(list, 2);
  pigeonResult.metadata = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable PGNInputImageMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNInputImageMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[PGNInputImageTypeBox alloc] initWithValue:self.type],
    self.filePath ?: [NSNull null],
    self.bytes ?: [NSNull null],
    self.metadata ?: [NSNull null],
  ];
}
@end

@implementation PGNImageLabelerOptionsMessage
+ (instancetype)makeWithConfidenceThreshold:(double )confidenceThreshold
    type:(PGNImageLabelerType)type {
  PGNImageLabelerOptionsMessage* pigeonResult = [[PGNImageLabelerOptionsMessage alloc] init];
  pigeonResult.confidenceThreshold = confidenceThreshold;
  pigeonResult.type = type;
  return pigeonResult;
}
+ (PGNImageLabelerOptionsMessage *)fromList:(NSArray<id> *)list {
  PGNImageLabelerOptionsMessage *pigeonResult = [[PGNImageLabelerOptionsMessage alloc] init];
  pigeonResult.confidenceThreshold = [GetNullableObjectAtIndex(list, 0) doubleValue];
  PGNImageLabelerTypeBox *boxedPGNImageLabelerType = GetNullableObjectAtIndex(list, 1);
  pigeonResult.type = boxedPGNImageLabelerType.value;
  return pigeonResult;
}
+ (nullable PGNImageLabelerOptionsMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNImageLabelerOptionsMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.confidenceThreshold),
    [[PGNImageLabelerTypeBox alloc] initWithValue:self.type],
  ];
}
@end

@implementation PGNImageLabelMessage
+ (instancetype)makeWithConfidence:(double )confidence
    label:(NSString *)label
    index:(NSInteger )index {
  PGNImageLabelMessage* pigeonResult = [[PGNImageLabelMessage alloc] init];
  pigeonResult.confidence = confidence;
  pigeonResult.label = label;
  pigeonResult.index = index;
  return pigeonResult;
}
+ (PGNImageLabelMessage *)fromList:(NSArray<id> *)list {
  PGNImageLabelMessage *pigeonResult = [[PGNImageLabelMessage alloc] init];
  pigeonResult.confidence = [GetNullableObjectAtIndex(list, 0) doubleValue];
  pigeonResult.label = GetNullableObjectAtIndex(list, 1);
  pigeonResult.index = [GetNullableObjectAtIndex(list, 2) integerValue];
  return pigeonResult;
}
+ (nullable PGNImageLabelMessage *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [PGNImageLabelMessage fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    @(self.confidence),
    self.label ?: [NSNull null],
    @(self.index),
  ];
}
@end

@interface PGNMessagesPigeonCodecReader : FlutterStandardReader
@end
@implementation PGNMessagesPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[PGNInputImageTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[PGNImageLabelerTypeBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 131: 
      return [PGNInputImageMetadataMessage fromList:[self readValue]];
    case 132: 
      return [PGNInputImageMessage fromList:[self readValue]];
    case 133: 
      return [PGNImageLabelerOptionsMessage fromList:[self readValue]];
    case 134: 
      return [PGNImageLabelMessage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface PGNMessagesPigeonCodecWriter : FlutterStandardWriter
@end
@implementation PGNMessagesPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[PGNInputImageTypeBox class]]) {
    PGNInputImageTypeBox *box = (PGNInputImageTypeBox *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[PGNImageLabelerTypeBox class]]) {
    PGNImageLabelerTypeBox *box = (PGNImageLabelerTypeBox *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[PGNInputImageMetadataMessage class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PGNInputImageMessage class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PGNImageLabelerOptionsMessage class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[PGNImageLabelMessage class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface PGNMessagesPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation PGNMessagesPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[PGNMessagesPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[PGNMessagesPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *PGNGetMessagesCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    PGNMessagesPigeonCodecReaderWriter *readerWriter = [[PGNMessagesPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpPGNImageLabelDetectorApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNImageLabelDetectorApi> *api) {
  SetUpPGNImageLabelDetectorApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpPGNImageLabelDetectorApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNImageLabelDetectorApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.handleDetection", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PGNGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(handleDetectionInputImage:completion:)], @"PGNImageLabelDetectorApi api (%@) doesn't respond to @selector(handleDetectionInputImage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        PGNInputImageMessage *arg_inputImage = GetNullableObjectAtIndex(args, 0);
        [api handleDetectionInputImage:arg_inputImage completion:^(NSArray<PGNImageLabelMessage *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.create", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PGNGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createOptions:error:)], @"PGNImageLabelDetectorApi api (%@) doesn't respond to @selector(createOptions:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        PGNImageLabelerOptionsMessage *arg_options = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api createOptions:arg_options error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.manageModel", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PGNGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(manageModelModelName:error:)], @"PGNImageLabelDetectorApi api (%@) doesn't respond to @selector(manageModelModelName:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_modelName = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api manageModelModelName:arg_modelName error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.google_mlkit_commons.ImageLabelDetectorApi.closeDetector", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:PGNGetMessagesCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(closeDetectorId:error:)], @"PGNImageLabelDetectorApi api (%@) doesn't respond to @selector(closeDetectorId:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_id = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api closeDetectorId:arg_id error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
